# DataSource Config
spring:
  datasource:
    # driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/mybatis_plus
    # 日志记录
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/mybatis_plus?verifyServerCertificate=false&useSSL=false
    username: root
    password: root
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

  # 配置定时任务
  quartz:
    job-store-type: JDBC #数据库存储quartz任务配置
    jdbc:
      initialize-schema: NEVER #自动初始化表结构，第一次启动的时候这里写always

# mybatis-plus
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml # mapper
  global-config:
    db-config:
      id-type: auto # id自增
    banner: true # 启动logo

# 文件上传路径
file:
  upload-dir: E:\tmp\file

# Actuator服务监控配置
# http:/host:port/actuator/health
# 打开详细信息
management:
  endpoint:
    health:
      show-details: always
  # 开启更多端口
  endpoints:
    web:
      exposure:
        include: '*'
# 设置服务信息
# http:/host:port/actuator/info
info:
  app-name: spring-boot-actuator-demo
  description: spring-boot-actuator-demo indexs monitor
